Merge all firmware linters steps into one job

diff --git a/.github/workflows/firmware_build_lint.yml b/.github/workflows/firmware_build_lint.yml
--- a/.github/workflows/firmware_build_lint.yml
+++ b/.github/workflows/firmware_build_lint.yml
@@ -12,6 +12,8 @@ on:
       - '.github/workflows/firmware_build_lint.yml'
 
 jobs:
+
+
 #
 # Build the firmware on Linux and Windows
 #
@@ -90,8 +92,8 @@ jobs:
 #
 # Run code quality and documentation checks
 #
-  clang-tidy:
-    name: Code Quality (clang-tidy 19)
+  code-quality:
+    name: Linters and documentation tools
     runs-on: ubuntu-latest
     needs: build
     steps:
@@ -99,6 +101,7 @@ jobs:
         uses: actions/checkout@v4
         with:
             submodules: recursive
+            lfs: false
 
       - name: Download the saved CMake configuration folder
         uses: actions/download-artifact@v4
@@ -115,13 +118,20 @@ jobs:
       - name: Check the GNU Arm Embedded Toolchain triplet
         run: ls -la ${{ steps.arm-none-eabi-gcc-action.outputs.path }}/../arm-none-eabi
 
-      - name: Install clang-tidy
-        run: sudo apt-get install -y clang-19 clang-tidy-19
+      - name: Install other tools
+        run: |
+              sudo apt-get install -y clang-19 clang-tidy-19 cppcheck flawfinder doxygen
+              sudo pip install lizard
 
-      - name: Remove "-fanalyzer" from compile_commands.json
+      - name: Cleanup compile_commands.json for clang-tidy
         run: sed -i 's/-fanalyzer//g' ${{github.workspace}}/firmware/build/Debug/compile_commands.json
 
+      - name: Create CPPcheck build directory
+        run: mkdir -p ${{github.workspace}}/firmware/config-cppcheck-build-dir/
+
       - name: run clang-tidy
+        id: clang
+        continue-on-error: true
         run:  >
               /usr/bin/run-clang-tidy-19
               -quiet
@@ -132,29 +142,9 @@ jobs:
               -header-filter=.*
               "(Hardware|UI)"
 
-  cppcheck:
-    name: Coding constructs (Cppcheck)
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-            submodules: recursive
-
-      - name: Download the saved CMake configuration folder
-        uses: actions/download-artifact@v4
-        with:
-          name: build-Debug
-          path: ${{github.workspace}}/firmware/build/Debug
-
-      - name: Install CppCheck
-        run: sudo apt-get install -y cppcheck
-
-      - name: Create CPPcheck build directory
-        run: mkdir -p ${{github.workspace}}/firmware/config-cppcheck-build-dir/
-
       - name: Run CppCheck
+        id: cppcheck
+        continue-on-error: true
         run:  >
               cppcheck
               --enable=all
@@ -174,49 +164,31 @@ jobs:
               --suppress=missingInclude
               --suppress=unusedFunction
 
-  flawfinder:
-    name: Security weakness (Flawfinder)
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-            submodules: recursive
-
-      - name: Run flawfinder
-        uses: david-a-wheeler/flawfinder@2.0.19
-        with:
-          arguments: firmware/Hardware/
-
-  lizard:
-    name: Cyclomatic complexity (Lizard)
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-            submodules: recursive
+      - name: Run Flawfinder
+        id: flawfinder
+        continue-on-error: true
+        run: |
+          flawfinder firmware/Hardware/
+          flawfinder firmware/UI/
 
       - name: Run Lizard
-        uses: Uno-Takashi/Lizard-Runner@v3
-        with:
-          path: firmware/Hardware/
-          language: cpp
-
-  doxygen:
-    name: Documentation (Doxygen)
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-        with:
-            submodules: recursive
-
-      - name: Install Doxygen
-        run: sudo apt-get install -y doxygen
+        id: lizard
+        continue-on-error: true
+        run: |
+          lizard --languages cpp firmware/Hardware/ firmware/UI/
 
       - name: Run Doxygen
+        id: doxygen
+        continue-on-error: true
         run: doxygen firmware/resources/Doxyfile
+
+      - name: Final result
+        run: |
+          if [ "${{ steps.clang.outcome }}" != "success" ] || \
+            [ "${{ steps.cppcheck.outcome }}" != "success" ] || \
+            [ "${{ steps.flawfinder.outcome }}" != "success" ] || \
+            [ "${{ steps.lizard.outcome }}" != "success" ] || \
+            [ "${{ steps.doxygen.outcome }}" != "success" ]; then
+            echo "::error::At least one tool failed"
+            exit 1
+          fi
