chore: unify config files and scripts + fix linter issues (#76)

diff --git a/.github/workflows/pcb_production_files.yml b/.github/workflows/pcb_production_files.yml
--- a/.github/workflows/pcb_production_files.yml
+++ b/.github/workflows/pcb_production_files.yml
@@ -18,9 +18,10 @@ on:
     - cron: "0 3 1 * *" #Automatically run at 03:00 every 1st of the month
 
 env:
-  SCH_PATH: ${{github.workspace}}/pcb
-  PROD_PATH: ${{ github.workspace }}/pcb/production_files
-  GBR_PATH: ${{ github.workspace }}/pcb/gerber
+  SCH_PATH: ${{github.workspace}}/leany/pcb
+  PROD_PATH: ${{ github.workspace }}/leany/pcb/production_files
+  GBR_PATH: ${{ github.workspace }}/leany/pcb/gerber
+  REPO_PATH: ${{github.workspace}}/leany
   SCH_FILE: leany.kicad_sch
   PCB_FILE: leany.kicad_pcb
   ERC_FILE: erc.json
@@ -38,13 +39,25 @@ jobs:
           options: --user root -v ${{ github.workspace }}:${{ github.workspace }}
 
         steps:
-          - name: Install jq json viewer
+          - name: Install jq json viewer and git-lfs
             run: |
                   sudo apt-get update
-                  sudo apt-get install -y jq
+                  sudo apt-get install -y jq git-lfs
+                  git lfs install
 
-          - name: Checkout the repository
-            uses: actions/checkout@v4
+          #actions/checkout cannot be used because it has its own context and will not recognise git-lfs
+          - name: Clone repository with LFS
+            env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            run: |
+              git clone https://x-access-token:${GITHUB_TOKEN}@github.com/gilleshenrard/leany.git
+              cd leany
+              git lfs pull
+
+          - name: Check LFS files
+            working-directory: ${{env.REPO_PATH}}
+            run:  |
+                  git lfs ls-files
           
           - name: Copy the KiCad configuration to the docker container
             run:  |
@@ -70,6 +83,7 @@ jobs:
 
           - name: Run Electrical Rules Check (ERC)
             id: erc
+            continue-on-error: true
             run:  >
                   kicad-cli sch erc
                   --output ${{env.SCH_PATH}}/${{env.ERC_FILE}}
@@ -78,7 +92,7 @@ jobs:
                   ${{env.SCH_PATH}}/${{env.SCH_FILE}}
 
           - name: Summarize ERC report
-            if: ${{ failure() && steps.erc.conclusion == 'failure' }}
+            if: ${{ steps.erc.outcome == 'failure' }}
             run: |
               echo "========== ERC Violations =========="
               erc_json=$(cat ${{ env.SCH_PATH }}/${{ env.ERC_FILE }})
@@ -105,13 +119,14 @@ jobs:
 
           - name: Upload ERC report if ERC failed
             uses: actions/upload-artifact@v4
-            if: ${{ failure() && steps.erc.conclusion == 'failure' }}
+            if: ${{ steps.erc.outcome == 'failure' }}
             with:
                 name: ${{env.ERC_FILE}}
                 path: ${{env.SCH_PATH}}/${{env.ERC_FILE}}
 
           - name: Run JLCPCB Design Rules Check (DRC)
             id: drc
+            continue-on-error: true
             run:  >
                   kicad-cli pcb drc
                   --output ${{env.SCH_PATH}}/${{env.DRC_FILE}}
@@ -120,7 +135,7 @@ jobs:
                   ${{env.SCH_PATH}}/${{env.PCB_FILE}}
 
           - name: Summarize DRC report
-            if: ${{ failure() && steps.drc.conclusion == 'failure' }}
+            if: ${{ steps.drc.outcome == 'failure' }}
             run: |
               echo "========== DRC Violations =========="
               drc_json=$(cat ${{ env.SCH_PATH }}/${{ env.DRC_FILE }})
@@ -148,10 +163,26 @@ jobs:
 
           - name: Upload DRC report if DRC failed
             uses: actions/upload-artifact@v4
-            if: ${{ failure() && steps.drc.conclusion == 'failure' }}
+            if: ${{ steps.drc.outcome == 'failure' }}
             with:
               name: ${{env.DRC_FILE}}
               path: ${{env.SCH_PATH}}/${{env.DRC_FILE}}
+
+          - name: Final result
+            run: |
+              failed=0
+    
+              if [ "${{ steps.erc.outcome }}" != "success" ]; then
+                echo "::error::ERC failed"
+                failed=1
+              fi
+              if [ "${{ steps.drc.outcome }}" != "success" ]; then
+                echo "::error::DRC failed"
+                failed=1
+              fi
+              if [ $failed -eq 1 ]; then
+                exit 1
+              fi
 
 
     jlcpcb:
@@ -163,8 +194,20 @@ jobs:
         options: --user root -v ${{ github.workspace }}:${{ github.workspace }}
 
       steps:
-        - name: Checkout the repository
-          uses: actions/checkout@v4
+        - name: Install git-lfs
+          run: |
+                sudo apt-get update
+                sudo apt-get install -y git-lfs
+                git lfs install
+
+        #actions/checkout cannot be used because it has its own context and will not recognise git-lfs
+        - name: Clone repository with LFS
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          run: |
+            git clone https://x-access-token:${GITHUB_TOKEN}@github.com/gilleshenrard/leany.git
+            cd leany
+            git lfs pull
 
         - name: Create the export directories
           run: |
